### ISSUE TITLE
1.7.10 BUG

### ISSUE THREAD

**Issue by Xiazihong** [frengor/VisualFixer#2]
`[16:54:50] [Server thread/INFO]: [VisualFixer] Enabling VisualFixer v2.2.2
[16:54:50] [Server thread/ERROR]: Error occurred while enabling VisualFixer v2.2.2 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.fren_gor.visualFixer.Main.onEnable(Main.java:90) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:359) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:420) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:352) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:507) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:481) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:441) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:353) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException`

**Comment by frengor** [comment]
Fixed
